version: '3.8'

services:
  db-new:
    image: postgres:latest
    container_name: mun-db-new
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: mun-nginx
    ports:
      - "6060:80"
    volumes:
      - "./storage:/usr/share/nginx/html:ro"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
volumes:
  postgres_data_new: